plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.6
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'vendor/bundle/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
  SuggestExtensions: false

# --- テストを優先 ---
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false

# --- 複雑さ・長さを緩和（concealed防止で1ブロックに統合）---
Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'controllers/**/*.rb'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'
    - 'controllers/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'controllers/**/*.rb'
    - 'config/environments/*.rb'
    - 'db/**/*.rb'

# --- レイアウト系 ---
Layout/TrailingWhitespace:
  Enabled: true
Layout/EmptyLines:
  Enabled: false
